=== sBohTor/XML_Rep_UD4/Act7/Editorial.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
 <xs:element name="informeVentas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="cabecera">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titulo" type="xs:string"/>
              <xs:element name="descripcion" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="datos">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="region" maxOccurs="unbounded">
                <xs:complexType>
                 <xs:sequence>
                    <xs:element name="trimestre" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="librosVendidos" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="numero" type="xs:int"/>
                      </xs:complexType>
                    </xs:element>
                 </xs:sequence>
                 <xs:attribute name="nombre" type="xs:string"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="fecha" type="xs:string"/>
    </xs:complexType>
 </xs:element>
</xs:schema>

=== sBohTor/XML_Rep_UD4/Act7/Editorial-x.xml
<?xml version="1.0" encoding="UTF-8"?>
<informeVentas fecha="30/12/2009" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Editorial.xsd">

    <cabecera>
      <titulo>Informe regional del ventas</titulo>
      <descripcion>informe de ventas para las regiones Norte, Centro y Sur</descripcion>
    </cabecera>
    <datos>
      <region nombre="Norte">
        <trimestre numero="1">
          <librosVendidos>24000</librosVendidos>
        </trimestre>
        <trimestre numero="2">
          <librosVendidos>38600</librosVendidos>
        </trimestre>
        <trimestre numero="3">
          <librosVendidos>NO_INFO</librosVendidos>
        </trimestre>
        <trimestre numero="4">
          <librosVendidos>NO_INFO</librosVendidos>
        </trimestre>
      </region>
      <region nombre="Centro">
        <trimestre numero="1">
          <librosVendidos>NO_INFO</librosVendidos>
        </trimestre>
        <trimestre numero="2">
          <librosVendidos>16080</librosVendidos>
        </trimestre>
        <trimestre numero="3">
          <librosVendidos>25000</librosVendidos>
        </trimestre>
        <trimestre numero="4">
          <librosVendidos>29000</librosVendidos>
        </trimestre>
      </region>
      <region nombre="Sur">
        <trimestre numero="1">
          <librosVendidos>27000</librosVendidos>
        </trimestre>
        <trimestre numero="2">
          <librosVendidos>31400</librosVendidos>
        </trimestre>
        <trimestre numero="3">
          <librosVendidos>40100</librosVendidos>
        </trimestre>
        <trimestre numero="4">
          <librosVendidos>30000</librosVendidos>
        </trimestre>
      </region>
    </datos>
   </informeVentas>
