=== sBohTor/XML_Rep_UD4/Act7/Editorial.dtd
<!ELEMENT informeVentas (cabecera, tabla)>
<!ATTLIST informeVentas fecha CDATA #REQUIRED>

<!ELEMENT cabecera (titulo, descripcion)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>

<!ELEMENT tabla (datos)>
<!ELEMENT datos (region+)>

<!ELEMENT region (trimestre+)>
<!ATTLIST region nombre CDATA #REQUIRED>

<!ELEMENT trimestre (librosVendidos)>
<!ATTLIST trimestre numero CDATA #REQUIRED>

<!ELEMENT librosVendidos (#PCDATA)>

=== sBohTor/XML_Rep_UD4/Act7/Editorial-d.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE informeVentas SYSTEM "Editorial.dtd">


<informeVentas fecha="30/12/2009">
    <cabecera>
        <titulo>Informe regional del ventas</titulo>
        <descripcion>informe de ventas para las regiones Norte, Centro y Sur</descripcion>
    </cabecera>
    <tabla>
        <datos>
            <region nombre="Norte">
                <trimestre numero="1">
                    <librosVendidos>24000</librosVendidos>
                </trimestre>
                <trimestre numero="2">
                    <librosVendidos>38600</librosVendidos>
                </trimestre>
                <trimestre numero="3">
                    <librosVendidos>NO_INFO</librosVendidos>
                </trimestre>
                <trimestre numero="4">
                    <librosVendidos>NO_INFO</librosVendidos>
                </trimestre>
            </region>
            <region nombre="Centro">
                <trimestre numero="1">
                    <librosVendidos>NO_INFO</librosVendidos>
                </trimestre>
                <trimestre numero="2">
                    <librosVendidos>16080</librosVendidos>
                </trimestre>
                <trimestre numero="3">
                    <librosVendidos>25000</librosVendidos>
                </trimestre>
                <trimestre numero="4">
                    <librosVendidos>29000</librosVendidos>
                </trimestre>
            </region>
            <region nombre="Sur">
                <trimestre numero="1">
                    <librosVendidos>27000</librosVendidos>
                </trimestre>
                <trimestre numero="2">
                    <librosVendidos>31400</librosVendidos>
                </trimestre>
                <trimestre numero="3">
                    <librosVendidos>40100</librosVendidos>
                </trimestre>
                <trimestre numero="4">
                    <librosVendidos>30000</librosVendidos>
                </trimestre>
            </region>
        </datos>
    </tabla>
</informeVentas>
