=== sBohTor/XML_Rep_UD4/Act2/Concesionario.dtd
<!ELEMENT Concesionario (coches*)>
<!ELEMENT coches (codigoCoche,marca,modelo,matricula,potencia,plazas,numeroPuertas)>
<!ELEMENT codigoCoche (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT matricula (#PCDATA)> 
<!ELEMENT potencia (#PCDATA)> 
<!ELEMENT plazas (#PCDATA)> 
<!ELEMENT numeroPuertas (#PCDATA)>

=== sBohTor/XML_Rep_UD4/Act3/Concesionario.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Concesionario SYSTEM "../Act2/Concesionario.dtd">

<Concesionario>  
    <coches>
        <codigoCoche>0</codigoCoche>
        <marca>BMW</marca>
        <modelo>1</modelo>
        <matricula>3323 NVK</matricula>
        <potencia>405CV</potencia>
        <plazas>4</plazas>
        <numeroPuertas>5</numeroPuertas>
    </coches>
    <coches>
        <codigoCoche>1</codigoCoche>
        <marca>Lamborguini</marca>
        <modelo>Huracan</modelo>
        <matricula>1233 CCK</matricula>
        <potencia>579CV</potencia>
        <plazas>2</plazas>
        <numeroPuertas>3</numeroPuertas>
    </coches>
    <coches>
        <codigoCoche>2</codigoCoche>
        <marca>BMW</marca>
        <modelo>1</modelo>
        <matricula>3323 NVK</matricula>
        <potencia>405CV</potencia>
        <plazas>4</plazas>
        <numeroPuertas>5</numeroPuertas>
    </coches>
    <coches>
        <codigoCoche>3</codigoCoche>
        <marca>Hyundai</marca>
        <modelo>Coupe V6</modelo>
        <matricula>0987 RTX</matricula>
        <potencia>170CV</potencia>
        <plazas>4</plazas>
        <numeroPuertas>3</numeroPuertas>
    </coches>
</Concesionario>
