=== sBohTor/XML_Rep_UD4/Act2/Mej/Estudiantes.dtd
<!ELEMENT Estudiantes (estudiante+)>
<!ELEMENT estudiante (nombre, edad, carrera, universidad, promedio)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT carrera (#PCDATA)>
<!ELEMENT universidad (#PCDATA)>
<!ELEMENT promedio (#PCDATA)>

=== sBohTor/XML_Rep_UD4/Act3/Mej/Estudiantes-d.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Estudiantes SYSTEM "..\..\Act2\Mej\Estudiantes.dtd">

<Estudiantes>
    <estudiante>
        <nombre>Juan Pérez</nombre>
        <edad>20</edad>
        <carrera>Ingeniería en Computación</carrera>
        <universidad>Universidad XYZ</universidad>
        <promedio>8.5</promedio>
    </estudiante>
    <estudiante>
        <nombre>Ana Sánchez</nombre>
        <edad>22</edad>
        <carrera>Derecho</carrera>
        <universidad>Universidad ABC</universidad>
        <promedio>9.0</promedio>
    </estudiante>
    <estudiante>
        <nombre>Carlos López</nombre>
        <edad>21</edad>
        <carrera>Medicina</carrera>
        <universidad>Universidad DEF</universidad>
        <promedio>8.8</promedio>
    </estudiante>
    <estudiante>
        <nombre>Maria García</nombre>
        <edad>23</edad>
        <carrera>Arquitectura</carrera>
        <universidad>Universidad GHI</universidad>
        <promedio>8.7</promedio>
    </estudiante>
    <estudiante>
        <nombre>Pedro Martínez</nombre>
        <edad>24</edad>
        <carrera>Periodismo</carrera>
        <universidad>Universidad JKL</universidad>
        <promedio>8.9</promedio>
    </estudiante>
</Estudiantes>
