=== sBohTor/XML_Rep_UD4/Act1/Mej1/BDsms-mejora-d.dtd
<!ELEMENT BDsms (registro*)>
<!ELEMENT registro (numero, fechaRegistrada, horaRegistrada, texto)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT fechaRegistrada (#PCDATA)>
<!ELEMENT horaRegistrada (#PCDATA)>
<!ELEMENT texto (#PCDATA)>

=== sBohTor/XML_Rep_UD4/Act1/Mej1/BDsms-mejora-d.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE BDsms SYSTEM "BDsms-mejora-d.dtd">

<BDsms>
 <registro>
     <numero>123456789</numero>
     <fechaRegistrada>1/1/2000</fechaRegistrada>
     <horaRegistrada>12:00</horaRegistrada>
     <texto>Nuevo mensaje</texto>
 </registro>
 <registro>
     <numero>987654321</numero>
     <fechaRegistrada>2/2/2002</fechaRegistrada>
     <horaRegistrada>13:00</horaRegistrada>
     <texto>Otro nuevo mensaje</texto> 
 </registro>
 <registro>
     <numero>112233445</numero>
     <fechaRegistrada>3/3/2003</fechaRegistrada>
     <horaRegistrada>14:00</horaRegistrada>
     <texto>Y otro nuevo mensaje</texto>
 </registro>
</BDsms>
